name: "Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: deadcache
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell -p jq
    - run: nix build .#nixosConfigurations.deadPc.config.system.build.toplevel | cachix push deadcache
    - run: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push mycache
    - run: nix-shell --run "echo OK"